-- ============================================
-- TABLES DE BASE - SYSTÈME TAXI-BROUSSE
-- ============================================

-- ============================================
-- 1. GESTION DES CARBURANTS
-- ============================================
CREATE TABLE Carburant_Type
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle      VARCHAR(255)   NOT NULL UNIQUE,
    dernier_taux DECIMAL(15, 2) NOT NULL CHECK (dernier_taux > 0)
);

CREATE TABLE Carburant_Mouvement_Taux
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carburant_type BIGINT         NOT NULL,
    ancien_taux       DECIMAL(15, 2) NOT NULL CHECK (ancien_taux > 0),
    nouveau_taux      DECIMAL(15, 2) NOT NULL CHECK (nouveau_taux > 0),
    date_mouvement    TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_carburant_type) REFERENCES Carburant_Type (id)
);

CREATE INDEX idx_carburant_mvt_date ON Carburant_Mouvement_Taux (date_mouvement DESC);

-- ============================================
-- 2. GESTION DES DEVISES
-- ============================================
CREATE TABLE Devise
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle      VARCHAR(255)   NOT NULL UNIQUE,
    dernier_taux DECIMAL(15, 4) NOT NULL CHECK (dernier_taux > 0)
);

CREATE TABLE Devise_Mouvement_Taux
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_devise      BIGINT         NOT NULL,
    ancien_taux    DECIMAL(15, 4) NOT NULL CHECK (ancien_taux > 0),
    nouveau_taux   DECIMAL(15, 4) NOT NULL CHECK (nouveau_taux > 0),
    date_mouvement TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_devise) REFERENCES Devise (id)
);

CREATE INDEX idx_devise_mvt_date ON Devise_Mouvement_Taux (date_mouvement DESC);

-- ============================================
-- 3. GESTION DES VÉHICULES
-- ============================================
CREATE TABLE Vehicule_Type
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Vehicule_Statut
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL UNIQUE
);

-- CORRECTION : Retrait de id_vehicule_statut
CREATE TABLE Vehicule
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_type                 BIGINT       NOT NULL,
    id_type_carburant       BIGINT       NOT NULL,
    marque                  VARCHAR(255) NOT NULL,
    modele                  VARCHAR(255) NOT NULL,
    maximum_passager        INTEGER      NOT NULL CHECK (maximum_passager > 0),
    immatriculation         VARCHAR(50)  NOT NULL UNIQUE,
    capacite_carburant      DECIMAL(10, 2) CHECK (capacite_carburant > 0),
    depense_carburant_100km DECIMAL(10, 2) CHECK (depense_carburant_100km > 0),
    FOREIGN KEY (id_type) REFERENCES Vehicule_Type (id),
    FOREIGN KEY (id_type_carburant) REFERENCES Carburant_Type (id)
);

CREATE INDEX idx_vehicule_immat ON Vehicule (immatriculation);

-- CORRECTION : Renommage des colonnes pour cohérence
CREATE TABLE Vehicule_Mouvement_Statut
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_vehicule       BIGINT    NOT NULL,
    date_mouvement    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_ancien_statut  BIGINT,
    id_nouveau_statut BIGINT    NOT NULL,
    observation       TEXT,
    FOREIGN KEY (id_vehicule) REFERENCES Vehicule (id),
    FOREIGN KEY (id_ancien_statut) REFERENCES Vehicule_Statut (id),
    FOREIGN KEY (id_nouveau_statut) REFERENCES Vehicule_Statut (id)
);

CREATE INDEX idx_vehicule_mvt_date ON Vehicule_Mouvement_Statut (id_vehicule, date_mouvement DESC);

CREATE TABLE Vehicule_Entretien
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_vehicule        BIGINT         NOT NULL,
    motif              TEXT           NOT NULL,
    date_debut_entretien TIMESTAMP    NOT NULL,
    date_fin_entretien   TIMESTAMP,
    montant_depense    DECIMAL(15, 2) NOT NULL CHECK (montant_depense >= 0),
    FOREIGN KEY (id_vehicule) REFERENCES Vehicule (id),
    CHECK (date_fin_entretien IS NULL OR date_fin_entretien >= date_debut_entretien)
);

CREATE INDEX idx_entretien_vehicule ON Vehicule_Entretien (id_vehicule, date_debut_entretien DESC);

-- ============================================
-- 4. GESTION DES CHAUFFEURS
-- ============================================
CREATE TABLE Chauffeur_Statut
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL UNIQUE
);

-- CORRECTION : Retrait de id_chauffeur_statut
CREATE TABLE Chauffeur
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom            VARCHAR(255) NOT NULL,
    prenom         VARCHAR(255) NOT NULL,
    date_naissance DATE         NOT NULL CHECK (date_naissance < CURRENT_DATE),
    numero_permis  VARCHAR(50)  NOT NULL UNIQUE
);

CREATE INDEX idx_chauffeur_permis ON Chauffeur (numero_permis);

CREATE TABLE Chauffeur_Mouvement_Statut
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_chauffeur      BIGINT    NOT NULL,
    date_mouvement    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_ancien_statut  BIGINT,
    id_nouveau_statut BIGINT    NOT NULL,
    observation       TEXT,
    FOREIGN KEY (id_chauffeur) REFERENCES Chauffeur (id),
    FOREIGN KEY (id_ancien_statut) REFERENCES Chauffeur_Statut (id),
    FOREIGN KEY (id_nouveau_statut) REFERENCES Chauffeur_Statut (id)
);

CREATE INDEX idx_chauffeur_mvt_date ON Chauffeur_Mouvement_Statut (id_chauffeur, date_mouvement DESC);

-- ============================================
-- 5. GESTION GÉOGRAPHIQUE
-- ============================================
CREATE TABLE Province
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Region
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_province BIGINT       NOT NULL,
    nom         VARCHAR(255) NOT NULL,
    FOREIGN KEY (id_province) REFERENCES Province (id),
    UNIQUE (id_province, nom)
);

CREATE TABLE Ville
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_region BIGINT       NOT NULL,
    nom       VARCHAR(255) NOT NULL,
    FOREIGN KEY (id_region) REFERENCES Region (id),
    UNIQUE (id_region, nom)
);

CREATE INDEX idx_ville_region ON Ville (id_region);

-- ============================================
-- 6. GESTION DES LIGNES
-- ============================================
-- CORRECTION : Retrait de la redondance nom_ville
CREATE TABLE Ligne
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ville_depart  BIGINT         NOT NULL,
    id_ville_arrivee BIGINT         NOT NULL,
    distance_km      DECIMAL(10, 2) CHECK (distance_km > 0),
    FOREIGN KEY (id_ville_depart) REFERENCES Ville (id),
    FOREIGN KEY (id_ville_arrivee) REFERENCES Ville (id),
    CHECK (id_ville_depart != id_ville_arrivee),
    UNIQUE (id_ville_depart, id_ville_arrivee)
);

CREATE TABLE Ligne_Arret
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ville  BIGINT       NOT NULL,
    nom_arret VARCHAR(255) NOT NULL,
    FOREIGN KEY (id_ville) REFERENCES Ville (id),
    UNIQUE (id_ville, nom_arret)
);

CREATE TABLE Ligne_Detail
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ligne       BIGINT  NOT NULL,
    ordre          INTEGER NOT NULL CHECK (ordre > 0),
    id_ligne_arret BIGINT  NOT NULL,
    FOREIGN KEY (id_ligne) REFERENCES Ligne (id),
    FOREIGN KEY (id_ligne_arret) REFERENCES Ligne_Arret (id),
    UNIQUE (id_ligne, ordre),
    UNIQUE (id_ligne, id_ligne_arret)
);

-- ============================================
-- 7. GESTION DES TRAJETS
-- ============================================
CREATE TABLE Trajet_Statut
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Trajet
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ligne         BIGINT         NOT NULL,
    id_chauffeur     BIGINT         NOT NULL,
    id_vehicule      BIGINT         NOT NULL,
    nombre_passager  INTEGER        NOT NULL CHECK (nombre_passager >= 0),
    id_trajet_statut BIGINT         NOT NULL,
    datetime_depart  TIMESTAMP      NOT NULL,
    datetime_arrivee TIMESTAMP,
    frais_unitaire   DECIMAL(15, 2) NOT NULL CHECK (frais_unitaire >= 0),
    FOREIGN KEY (id_ligne) REFERENCES Ligne (id),
    FOREIGN KEY (id_chauffeur) REFERENCES Chauffeur (id),
    FOREIGN KEY (id_vehicule) REFERENCES Vehicule (id),
    FOREIGN KEY (id_trajet_statut) REFERENCES Trajet_Statut (id),
    CHECK (datetime_arrivee IS NULL OR datetime_arrivee > datetime_depart)
);

CREATE INDEX idx_trajet_dates ON Trajet (datetime_depart, datetime_arrivee);
CREATE INDEX idx_trajet_vehicule ON Trajet (id_vehicule, datetime_depart);
CREATE INDEX idx_trajet_chauffeur ON Trajet (id_chauffeur, datetime_depart);

CREATE TABLE Trajet_Mouvement_Statut
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_trajet         BIGINT    NOT NULL,
    date_mouvement    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_ancien_statut  BIGINT,
    id_nouveau_statut BIGINT    NOT NULL,
    observation       TEXT,
    FOREIGN KEY (id_trajet) REFERENCES Trajet (id),
    FOREIGN KEY (id_ancien_statut) REFERENCES Trajet_Statut (id),
    FOREIGN KEY (id_nouveau_statut) REFERENCES Trajet_Statut (id)
);

CREATE INDEX idx_trajet_mvt_date ON Trajet_Mouvement_Statut (id_trajet, date_mouvement DESC);

CREATE TABLE Trajet_Motif_Arret
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL UNIQUE
);

-- CORRECTION : Ajout de id_caisse
CREATE TABLE Trajet_Arret_Detail
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_trajet             BIGINT         NOT NULL,
    id_caisse             BIGINT,
    id_ville              BIGINT         NOT NULL,
    id_trajet_motif_arret BIGINT         NOT NULL,
    montant_depense       DECIMAL(15, 2) CHECK (montant_depense >= 0),
    datetime_debut        TIMESTAMP      NOT NULL,
    datetime_fin          TIMESTAMP,
    FOREIGN KEY (id_trajet) REFERENCES Trajet (id),
    FOREIGN KEY (id_ville) REFERENCES Ville (id),
    FOREIGN KEY (id_trajet_motif_arret) REFERENCES Trajet_Motif_Arret (id),
    CHECK (datetime_fin IS NULL OR datetime_fin >= datetime_debut)
);

CREATE INDEX idx_arret_trajet ON Trajet_Arret_Detail (id_trajet, datetime_debut);

-- NOUVEAU : Table pour la gestion du carburant
CREATE TABLE Trajet_Carburant_Detail
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_trajet                BIGINT         NOT NULL,
    id_caisse                BIGINT,
    id_ville                 BIGINT         NOT NULL,
    id_carburant_type        BIGINT         NOT NULL,
    datetime                 TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    quantite_carburant_ajoute DECIMAL(10, 2) NOT NULL CHECK (quantite_carburant_ajoute > 0),
    taux_carburant           DECIMAL(15, 2) NOT NULL CHECK (taux_carburant > 0),
    FOREIGN KEY (id_trajet) REFERENCES Trajet (id),
    FOREIGN KEY (id_ville) REFERENCES Ville (id),
    FOREIGN KEY (id_carburant_type) REFERENCES Carburant_Type (id)
);

CREATE INDEX idx_carburant_trajet ON Trajet_Carburant_Detail (id_trajet, datetime);

-- ============================================
-- 8. GESTION DES CLIENTS ET RÉSERVATIONS
-- ============================================
CREATE TABLE Type_Client
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Client
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_type_client BIGINT       NOT NULL DEFAULT 1,
    nom_client     VARCHAR(255) NOT NULL DEFAULT 'Default',
    telephone      VARCHAR(50),
    email          VARCHAR(255),
    FOREIGN KEY (id_type_client) REFERENCES Type_Client (id)
);

CREATE TABLE Type_Mouvement
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Mode_Paiement
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Reservation_Status
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Trajet_Reservation
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_client                BIGINT         NOT NULL,
    id_trajet                BIGINT         NOT NULL,
    id_reservation_statut    BIGINT         NOT NULL,
    numero_siege             VARCHAR(50),
    nom_passager             VARCHAR(255)   NOT NULL,
    montant                  DECIMAL(15, 2) NOT NULL CHECK (montant >= 0),
    date_reservation         TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nombre_place_reservation INTEGER        NOT NULL DEFAULT 1 CHECK (nombre_place_reservation > 0),
    FOREIGN KEY (id_client) REFERENCES Client (id),
    FOREIGN KEY (id_trajet) REFERENCES Trajet (id),
    FOREIGN KEY (id_reservation_statut) REFERENCES Reservation_Status (id),
    UNIQUE (id_trajet, numero_siege)
);

CREATE INDEX idx_reservation_trajet ON Trajet_Reservation (id_trajet, date_reservation);

CREATE TABLE Trajet_Reservation_Mouvement_Status
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_trajet_reservation BIGINT    NOT NULL,
    date_mouvement       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_ancien_statut     BIGINT,
    id_nouveau_statut    BIGINT    NOT NULL,
    observation          TEXT,
    FOREIGN KEY (id_trajet_reservation) REFERENCES Trajet_Reservation (id),
    FOREIGN KEY (id_ancien_statut) REFERENCES Reservation_Status (id),
    FOREIGN KEY (id_nouveau_statut) REFERENCES Reservation_Status (id)
);

-- NOUVEAU : Paiements liés aux réservations
CREATE TABLE Trajet_Reservation_Paiement
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_client             BIGINT         NOT NULL,
    id_trajet_reservation BIGINT         NOT NULL,
    id_caisse             BIGINT,
    montant               DECIMAL(15, 2) NOT NULL CHECK (montant > 0),
    id_mode_paiement      BIGINT         NOT NULL,
    date_paiement         TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_client) REFERENCES Client (id),
    FOREIGN KEY (id_trajet_reservation) REFERENCES Trajet_Reservation (id),
    FOREIGN KEY (id_mode_paiement) REFERENCES Mode_Paiement (id)
);

CREATE INDEX idx_reservation_paiement ON Trajet_Reservation_Paiement (id_trajet_reservation, date_paiement);

-- ============================================
-- 9. FINANCES
-- ============================================
CREATE TABLE Trajet_Finance
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_trajet         BIGINT         NOT NULL,
    montant           DECIMAL(15, 2) NOT NULL,
    id_type_mouvement BIGINT         NOT NULL,
    date_mouvement    TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_trajet) REFERENCES Trajet (id),
    FOREIGN KEY (id_type_mouvement) REFERENCES Type_Mouvement (id)
);

CREATE INDEX idx_finance_trajet ON Trajet_Finance (id_trajet, date_mouvement);

CREATE TABLE Prevision_Finance
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_trajet         BIGINT,
    id_entite_origine BIGINT,
    table_origine     VARCHAR(255),
    montant           DECIMAL(15, 2) NOT NULL CHECK (montant >= 0),
    id_type_mouvement BIGINT         NOT NULL,
    date              TIMESTAMP      NOT NULL,
    description       TEXT,
    FOREIGN KEY (id_trajet) REFERENCES Trajet (id),
    FOREIGN KEY (id_type_mouvement) REFERENCES Type_Mouvement (id)
);

CREATE INDEX idx_prevision_trajet ON Prevision_Finance (id_trajet, date);
CREATE INDEX idx_prevision_origine ON Prevision_Finance (table_origine, id_entite_origine);

CREATE TABLE Prevision_Trajet
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ligne         BIGINT         NOT NULL,
    id_chauffeur     BIGINT         NOT NULL,
    id_vehicule      BIGINT         NOT NULL,
    nombre_passager  INTEGER        NOT NULL CHECK (nombre_passager >= 0),
    id_trajet_statut BIGINT         NOT NULL,
    datetime_depart  TIMESTAMP      NOT NULL,
    datetime_arrivee TIMESTAMP,
    frais_unitaire   DECIMAL(15, 2) NOT NULL CHECK (frais_unitaire >= 0),
    FOREIGN KEY (id_ligne) REFERENCES Ligne (id),
    FOREIGN KEY (id_chauffeur) REFERENCES Chauffeur (id),
    FOREIGN KEY (id_vehicule) REFERENCES Vehicule (id),
    FOREIGN KEY (id_trajet_statut) REFERENCES Trajet_Statut (id),
    CHECK (datetime_arrivee IS NULL OR datetime_arrivee > datetime_depart)
);

-- ============================================
-- 10. CAISSE
-- ============================================
CREATE TABLE Caisse_Type
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Caisse
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caisse_type BIGINT         NOT NULL,
    nom            VARCHAR(255)   NOT NULL UNIQUE,
    solde_initial  DECIMAL(15, 2) NOT NULL CHECK (solde_initial >= 0),
    FOREIGN KEY (id_caisse_type) REFERENCES Caisse_Type (id)
);

CREATE TABLE Caisse_Mouvement
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caisse         BIGINT         NOT NULL,
    id_entite_origine BIGINT,
    table_origine     VARCHAR(255),
    id_type_mouvement BIGINT         NOT NULL,
    montant           DECIMAL(15, 2) NOT NULL CHECK (montant > 0),
    motif             TEXT,
    date_mouvement    TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_caisse) REFERENCES Caisse (id),
    FOREIGN KEY (id_type_mouvement) REFERENCES Type_Mouvement (id)
);

CREATE INDEX idx_caisse_mvt_date ON Caisse_Mouvement (id_caisse, date_mouvement DESC);
CREATE INDEX idx_caisse_origine ON Caisse_Mouvement (table_origine, id_entite_origine);

-- ============================================
-- AJOUT DES FOREIGN KEYS MANQUANTES
-- ============================================
ALTER TABLE Trajet_Arret_Detail ADD FOREIGN KEY (id_caisse) REFERENCES Caisse (id);
ALTER TABLE Trajet_Carburant_Detail ADD FOREIGN KEY (id_caisse) REFERENCES Caisse (id);
ALTER TABLE Trajet_Reservation_Paiement ADD FOREIGN KEY (id_caisse) REFERENCES Caisse (id);